// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkWLk8FaRo8A4ZQOHwmczY7E9R-uK1HWc',
    appId: '1:862461631739:web:fda736ad7b585568aa245e',
    messagingSenderId: '862461631739',
    projectId: 'statewatch-ea4af',
    authDomain: 'statewatch-ea4af.firebaseapp.com',
    storageBucket: 'statewatch-ea4af.appspot.com',
    measurementId: 'G-JPW3TS6KZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGRDQt3FG3itJODqZHRtdSOTWv5FuvcB8',
    appId: '1:862461631739:android:62d112544441d3b2aa245e',
    messagingSenderId: '862461631739',
    projectId: 'statewatch-ea4af',
    storageBucket: 'statewatch-ea4af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE_NN_Z8JBgZ0_7GxpUCj_oD1xdOSBfZ8',
    appId: '1:862461631739:ios:83b95aa5d4714a8caa245e',
    messagingSenderId: '862461631739',
    projectId: 'statewatch-ea4af',
    storageBucket: 'statewatch-ea4af.appspot.com',
    iosBundleId: 'com.technest.statewatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE_NN_Z8JBgZ0_7GxpUCj_oD1xdOSBfZ8',
    appId: '1:862461631739:ios:38f605cf3cea3581aa245e',
    messagingSenderId: '862461631739',
    projectId: 'statewatch-ea4af',
    storageBucket: 'statewatch-ea4af.appspot.com',
    iosBundleId: 'com.technest.statewatch.RunnerTests',
  );
}
